### ISSUE TITLE
Readme not precise about the meaning of the port config parameter

### ISSUE THREAD

**Issue by freaki2010** [LOENS2/pterodactyl_exporter#24]
**Describe the bug**
When I enter everything except the port into the config file the docker container starts and an error is shown when opening the logs. But when I enter the port as well only following output is shown.
```
docker compose up
[+] Running 1/0
 ✔ Container pterodactyl-exporter  Created                                                                                                                                                                    0.0s 
Attaching to pterodactyl-exporter
```

**To Reproduce**
- pull the latest docker image
- configure everything
- start the container.

**Expected behavior**
After I entered the port the docker container should start

 - Distribution: Debian GNU/Linux 12 (bookworm)
 - Python version: the one from your docker image :D
 - Prometheus version: 2.50.1
 - Pterodactyl Panel version: 1.11.3

**Additional context**

**Comment by LOENS2** [comment]
Well, based on what you tell me, I don't see any problem. If you don't configure a port the obviously fails to start, showing an error in the logs. When providing a complete config, compose does its startup procedure (showing to output you send me) and your good to go. When running without errors, the docker log is empty. That is the normal behaviour. 
Please further specify your problem, because I don't think I fully understand it.

**Comment by freaki2010** [comment]
The container isn't running. 
when I type in docker-compose up -d. it is stuck at Attaching to pterodactyl-exporter, like shown in the console output I pasted.

**Comment by LOENS2** [comment]
Ok, but does the exporter work while you're stuck on that message or not?

**Comment by LOENS2** [comment]
And did you try to run the exporter on a different device? Just to rule out your specific device.

**Comment by freaki2010** [comment]
okay yeah my bad... :D

Container is running, but the /metrics endpoint isn't working. 
I entered the port of the panel from which the login mask is available in the internet. 443
Or is it a special port the exporter need to connect to the panel?

**Comment by LOENS2** [comment]
The port of the exporter usually is 9531. This does in fact not refer to the panels api endpoint nor the login mask.

**Comment by LOENS2** [comment]
Ah now i see where the problem is coming from. In the README, I don't mention at all what the port option is actually for, so my bad. I just updated the README to contain the information in that

**Comment by freaki2010** [comment]
ah okay... Thank you very much! :)
I was a bit confused that I need to enter the port for the panel but now it makes sense ^^

**Comment by freaki2010** [comment]
Now everything is working fine.
Maybe you can set it as standard parameter to the config. with a comment :)

Thank you very much for this exporter!

**Comment by LOENS2** [comment]
I'll do that to prevent further confusion! Thank you for making me aware of that. I'll mark this issue as solved now.
