### ISSUE TITLE
Pterodactyl Exporter egg not working due to boolean values.

### ISSUE THREAD

**Issue by LOENS2** [LOENS2/pterodactyl_exporter#27]
With the release of version 1.0.0 the Pterodactyl Server Egg is now non-functional due to the the script's config parser only accepting the values `true` and `false`, however Pterodactyl fills the boolean values with `0` and `1` which leads to the script stopping immediately after starting it with the error:

```
Timestamp | Config Error:
        https: Please use a boolean value
``` 

The Pterodactyl team has no incentive to fix this issue even though users got multiple issues with that, probably because it has to do with laravel as described here: https://github.com/pterodactyl/panel/issues/4462. The workaround suggested there doesn't work either, as a string is a invalid value, too.

@freaki2010 What do you suggest to fix this?

**Comment by freaki2010** [comment]
I would suggest to parse the https config to bool if it's type int.
Same would be the case for ignore_ssl I guess.

Not a pretty solution but otherwise it wouldn't work for the egg. :D

So every int value != 0 will be true.

**Comment by freaki2010** [comment]
pterodactyl_exporter/dto/config.py
```
    @staticmethod
    def validate_https(value, **_) -> bool:
        if True is isinstance(value, int):
            return bool(value)
        if False is isinstance(value, bool):
            raise ValueError("https: Please use a boolean value")
        return value

    @staticmethod
    def validate_ignore_ssl(value, **_) -> bool:
        if True is isinstance(value, int):
            return bool(value)
        if False is isinstance(value, bool):
            raise ValueError("ignore_ssl: Please use a boolean value")
        return value
```

**Comment by freaki2010** [comment]
Create PR:
https://github.com/LOENS2/pterodactyl_exporter/pull/28

**Comment by LOENS2** [comment]
I don't think it is a pretty solution either, but that's the way things are.
