### ISSUE TITLE
Error Network

### ISSUE THREAD

**Issue by CodeExplorerX** [LOENS2/pterodactyl_exporter#29]
Error Network: PromQL info: metric might not be a counter, name does not end in _total/_sum/_count/_bucket: "pterodactyl_server_network_rx_mebibyte" (1:10)
![image](https://github.com/LOENS2/pterodactyl_exporter/assets/125815118/1e6d3669-51d7-4f1c-bed0-de80bb5b6cfa)
![image](https://github.com/LOENS2/pterodactyl_exporter/assets/125815118/96827e40-5a68-453c-98e6-d445f91b7c44)

**Comment by LOENS2** [comment]
Du you have an old version of prometheus installed? This could be related to a bug in prometheus: https://github.com/prometheus/prometheus/issues/12945. I don't have that error in my testing environment and from the looks of your diagrams, the metrics seem to be shown just fine.

**Comment by CodeExplorerX** [comment]
I apologize for not adding details. I have a new version of Prometheus installed. And the metrics are constantly at zero.

`prometheus, version 2.51.1 (branch: HEAD, revision: 855b5ac4b80956874eb1790a04c92327f2f99e38)
  build user:       root@35108a5d8f07
  build date:       20240328-09:31:42
  go version:       go1.22.1
  platform:         linux/386
  tags:             netgo,builtinassets,stringlabels`

**Comment by LOENS2** [comment]
It would be awesome, if you'd tell me which deployment type you use (docker/egg/bare metal) and which version of the exporter you are using.

**Comment by CodeExplorerX** [comment]
The problem was on my side, since the interface address for the containers was specified as localhost
![image](https://github.com/LOENS2/pterodactyl_exporter/assets/125815118/085a5e21-e7be-4d1c-a103-e7079a2fb8cf)
