### ISSUE TITLE
dont understand this error

### ISSUE THREAD

**Issue by DrTableBasse** [LOENS2/pterodactyl_exporter#3]
i create a good and clean config.yml w/ your example so i had this error :-/ 

```ts=2022-08-22T14:55:03.725Z caller=main.go:454 level=error msg="Error loading config (--config.file=/home/prometheus/pterodactyl_exporter/config.yml)" file=/home/prometheus/pterodactyl_exporter/config.yml err="parsing YAML file /home/prometheus/pterodactyl_exporter/config.yml: yaml: unmarshal errors:\n  line 1: field host not found in type config.plain\n  line 2: field api_key not found in type config.plain\n  line 3: field https not found in type config.plain"
```

any ideas ?

**Comment by LOENS2** [comment]
Which error? You posted an empty code field. Please be more precise.

**Comment by DrTableBasse** [comment]
Unit Testing:  pterodactyl_exporter/pterodactyl_exporter/config.yml
  FAILED:
yaml: unmarshal errors:
  line 1: field host not found in type main.unitTestFile
  line 2: field api_key not found in type main.unitTestFile
  line 3: field https not found in type main.unitTestFile


sorry sorry...

**Comment by DrTableBasse** [comment]
host: samuel-lab.freeboxos.fr
api_key: <my api key>
https: true

**Comment by LOENS2** [comment]
I assume that your yaml syntax isn't valid. Please check for wrong indentation. How did you create the file?

**Comment by LOENS2** [comment]
What I meant is:

- Which program did you use to create the file? (Nano Vi, Vim)
- Did you copy my sample file with the copy button of the code field?
- Did you enter the correct information?

**Comment by DrTableBasse** [comment]
i just follow the steps on repo... btw the first command with pip install doesn't work too... ill send u log if u want x) ill


I just nano to create file
i copy your sample file
yeah i entered the correct informations

**Comment by LOENS2** [comment]
Please send the log for the pip command.

You could download the config,yml from the releases with
`curl -o config.yml -fsSL https://github.com/LOENS2/pterodactyl_exporter/releases/download/0.1.0/config.yml`
and try again by filling in the host and api key

**Comment by DrTableBasse** [comment]
so i just follow step by step and now i have this error

prometheus@cleqn:~$ systemctl status pterodactyl_exporter.service
× pterodactyl_exporter.service - Prometheus Server
     Loaded: loaded (/etc/systemd/system/pterodactyl_exporter.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-08-26 15:32:55 UTC; 30s ago
    Process: 2666 ExecStart=pterodactyl_exporter --config-file=/home/prometheus/pterodactyl_exporter/config.yml (code=exited, status=1/FAILURE)
   Main PID: 2666 (code=exited, status=1/FAILURE)
        CPU: 69ms

**Comment by LOENS2** [comment]
Please excuse my late response. 
Well this doesn't tell me a lot. Just that the program crashed.

Please tell me how your put the Pterodactyl Exporter into service step by step. I have not yet been able to recreate this fault/bug so far, so please tell me anything that you did.

**Comment by LOENS2** [comment]
Did you fix it? If you're not responding anymore, I have to assume that your problem is already solved.
Please tell me if this is the case and how your status quo looks like. 
Otherwise I'm going to close this issue tagged "invalid".

If your issue is related to #4 than just install prometheus-client with pip.

If you need further help i recommend starting a discussion on that.
