### ISSUE TITLE
All servers are not displayed

### ISSUE THREAD

**Issue by CodeExplorerX** [LOENS2/pterodactyl_exporter#30]
I have 77 servers, so in Pterodactyl, due to their number, some of them are posted on the second page. And all the servers that are on the second page “pterodactyl_exporter” do not see them. I did the math and it only shows 51 servers. I tried reinstalling pterodactyl_exporter and changing the API key, but this did not change the situation.
![image](https://github.com/LOENS2/pterodactyl_exporter/assets/125815118/f551d436-5050-4550-bb61-e14a70035fae)
Pterodactyl_exporter version: 1.0.0
deployment type: bare metal

**Comment by CodeExplorerX** [comment]
I looked at the API and found out that ['meta']['pagination']['total_pages'] contains the number of pages. Therefore, to see the number of servers on the next page you need to specify the following URL:
/api/client/?type={self.config.server_list_type}&page=2
Hope this helps somehow

**Comment by LOENS2** [comment]
That should be a pretty straight forward fix to do.

**Comment by LOENS2** [comment]
Should be fixed with 89cb00f. Please tell me if it still doesn't work.

**Comment by CodeExplorerX** [comment]
After the update, pterodactyl_exporter apparently stopped accepting servers with the Cyrillic alphabet
![image](https://github.com/LOENS2/pterodactyl_exporter/assets/125815118/cfebf703-8cfa-4791-8f6b-71d6e2bfe2fa)

**Comment by CodeExplorerX** [comment]
> Well that is strange. I ony added another loop for the page index. I have to look for that error tomorrow.

I found out what the problem is. The server that caused the error is in "Suspended" mode. Because of this, pterodactyl_exporter hung on it because it could not get its metrics.

**Comment by LOENS2** [comment]
Ok. Thank you for letting me know. I'll add a check for suspension to mitigate that.

**Comment by LOENS2** [comment]
The suspended issue should be fixed in 6f78842. This was also the case with installing servers.

**Comment by CodeExplorerX** [comment]
> The suspended issue should be fixed in [6f78842](https://github.com/LOENS2/pterodactyl_exporter/commit/6f78842a6ea51c6a65bac66f9bfd095a9feaf2f5). This was also the case with installing servers.

It still collects information only from the first page. I tried changing the API key, deleting Prometheus data, running in docker, but it didn't help

**Comment by CodeExplorerX** [comment]
I turned to my friend for help and he helped me with this problem
`def get_metrics(self):
    self.metrics = Metrics()
    t1 = time.time()
    servers = self.fetch_server()
    total_servers = servers['meta']['pagination']['total']
    per_page = servers['meta']['pagination']['per_page']
    total_pages = (total_servers + per_page - 1) // per_page
    
    for page in range(1, total_pages + 1):
        servers_on_page = self.fetch_server(page=page)
        for server_data in servers_on_page.get('data', []):
            if not (bool(server_data['attributes']['is_suspended']) or
                    bool(server_data['attributes']['is_installing'])):
                self.process_servers(server_data)
                server_id = server_data['attributes']['identifier']
                resources = self.fetch_resources(server_id)
                self.process_resources(resources)
                self.fetch_last_backup_time(server_id)
    t2 = time.time()
    print(f"total= {t2 - t1}")
    return self.metrics

def fetch_server(self, page=1):
    url = f"{self.get_url()}/api/client/?type={self.config.server_list_type}&page={page}"
    response = requests.get(url, headers=self.headers, verify=not self.config.ignore_ssl)
    if response.status_code != 200:
        raise Exception(f"Error fetching servers: {response.text}")
    response.close()
    return response.json()
    
def fetch_resources(self, server_id):
    url = f"{self.get_url()}/api/client/servers/{server_id}/resources"
    response = requests.get(url, headers=self.headers, verify=not self.config.ignore_ssl)
    if response.status_code != 200:
        raise Exception(f"Fetch metrics for server {server_id}")
    response_data = response.json()
    response.close()
    return response_data["attributes"]["resources"]

def fetch_last_backup_time(self, server_id):
    url = f"{self.get_url()}/api/client/servers/{server_id}/backups?per_page=50"
    response = requests.get(url, headers=self.headers, verify=not self.config.ignore_ssl)
    if response.status_code != 200:
        raise Exception(f"Fetch last backup for server {server_id}")
    response_data = response.json()
    response.close()
    backups = response_data["data"]
    last_successful_backup = max(
        dateutil.parser.isoparse(backup["attributes"]["completed_at"]).timestamp()
        for backup in backups
        if backup["attributes"]["is_successful"]
    ) if backups else 0
    self.metrics.last_backup_time.append(last_successful_backup)`

**Comment by CodeExplorerX** [comment]
I asked my friend for help and he helped me with this problem.
https://pastebin.com/iXsg1ifA

**Comment by LOENS2** [comment]
I integrated the code you send me into the project. Should be working now.

**Comment by CodeExplorerX** [comment]
Error again😅
2024-04-05 17:55:22 | Init successful!
2024-04-05 17:55:23 | An error occurred:
        HTTPClient.fetch_resources() missing 1 required positional argument: 'page'
        
I checked the code that I gave you again, and everything works with it.

**Comment by LOENS2** [comment]
I think you just have to update again. I accidentally uploaded the non-working code.

**Comment by LOENS2** [comment]
The upload failed, so my bad. I'll upload the working version.

**Comment by LOENS2** [comment]
Should work now.

**Comment by CodeExplorerX** [comment]
> Should work now.

It worked!!!!
Thank you very much!!!🔥🔥🔥
