### ISSUE TITLE
Ports below 1024 are not supported any more

### ISSUE THREAD

**Issue by grimsi** [LOENS2/pterodactyl_exporter#32]
**Describe the bug**
The code rewrite in 51e9dbcd8a340b52901a37d7ed29f78b7258d7e9 introduced verification of the config.yml file (a good thing). However, the constraints for the port range is a bit limiting, because ports below 1025 are now not supported any more (they were supported before).
I can see no reason not to support priviliged ports (those from 0-1023), especially since the Pterodactyl panel is a web interface and the default HTTP ports are 80 and 443 (both below 1024).

**To Reproduce**
1. Set port to a value below 1025 in the config.yml
2. Start the container

**Expected behavior**
The exporter should start and function normally.

**Screenshots**
config.yml:
```yaml
host: pterodactyl-panel
port: 80
api_key: <REDACTED>
https: false
ignore_ssl: false
server_list_type: admin-all
```

Resulting log:
```
docker logs pterodactyl-exporter
2024-04-22 20:27:15 | Config Error:
        port: Please use a port between 1025 and 65535
Script stopped!
```

**Desktop (please complete the following information):**
 - OS: Unraid 6.12.9
 - Docker: version 24.0.9, build 2936816
 - Pterodactyl Exporter: loens2/pterodactyl_exporter:latest (should be 1.0.3)

**Comment by LOENS2** [comment]
I agree. I don't know why @freaki2010 added the check for unprivileged ports. For me, there's no obvious advantage of doing so.

**Comment by LOENS2** [comment]
This should be fixed now. I changed the range to Port 1 to 65535 which should allow for privileged use. Changed in 8896b87

**Comment by grimsi** [comment]
Thanks, it works now!
