### ISSUE TITLE
Adding pterodactyl port configuration

### ISSUE THREAD

**Issue by rurueuh** [LOENS2/pterodactyl_exporter#38]
**Is your feature request related to a problem?**
my pterodactyl server is not running on port 80 and 443

**Describe the solution you'd like**
add in config file a port variable for pterodactyl host port

**Describe alternatives you've considered**
X

**Additional context**
X

**Comment by LOENS2** [comment]
Merged in [c8309b7](https://github.com/LOENS2/pterodactyl_exporter/commit/c8309b7a36461d023f20ba805621bc18d67f3262)
