### ISSUE TITLE
Add Docker Image and Docker Hub

### ISSUE THREAD

**Issue by LOENS2** [LOENS2/pterodactyl_exporter#7]
@grimsi kindly added the Docker Image and Docker file already. https://github.com/LOENS2/pterodactyl_exporter/pull/5 

My turn is putting it on `hub.docker.com`. Imma post my progress here.

**Comment by LOENS2** [comment]
The Docker image is now built locally but not running, because the config file path does not exist.

**Comment by grimsi** [comment]
How are you running it? Are you using `docker run` or `docker compose up`?
It should run by just going inside the `docker` folder and running `docker compose up -d`.
I know Docker can be confusing if you never worked with it before, so if you have any question feel free to ask :)

**Comment by LOENS2** [comment]
I know. My problem is, that I tried to run it in WSL and created the config inside the docker directory. I have to move it and hopefully make it work like that.

**Comment by LOENS2** [comment]
Now, after moving the the config file one directory higher, it works like a charm.

**Comment by LOENS2** [comment]
Readme is now updated and contains a guide for running it with docker.
